In [1]:
import dataretrieval.nwis as nwis
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import folium
import mplleaflet
from selenium import webdriver

In [2]:
# calling specific data from USGS using NWIS function
# retrieves information from NWIS for the State of Utah




df = nwis.get_info(stateCd = 'UT')  
                             


#first row contains data available for the state of Utah in the NWIS database
#This includes the number of sites, the number of wells, the number of surface-water sites, the number
#of groundwater sites, the number of water-quality sites, and the number of other sites (such as atmospheric
#deposition sites, soil sites, and ecological sites).


#The second row contains information about the data availability for each year in the NWIS database for 
#the state of Utah. This includes the range of years for which data is available, the number of sites 
#with available data for each year, and the total number of measurements made for each year.


dfsites = df[0]

In [3]:
#subsetting only the groundwater sites in the dataframe:

dfsitesGW = dfsites[dfsites["site_tp_cd"] == "GW"]
dfsitesGW

,agency_cd,site_no,station_nm,site_tp_cd,lat_va,long_va,dec_lat_va,dec_long_va,coord_meth_cd,coord_acy_cd,...,local_time_fg,reliability_cd,gw_file_cd,nat_aqfr_cd,aqfr_cd,aqfr_type_cd,well_depth_va,hole_depth_va,depth_src_cd,project_no
993,USGS,365954110163301,(D-43-15)32dcd- 1,GW,365954.0,1101633.0,36.998334,-110.276521,M,S,...,Y,C,NNNNNNNN,N300COPLTS,310DCLL,U,120.0,120.0,R,474923900
994,USGS,370000113273301,(C-43-14)31ddd- 1,GW,370000.0,1132733.0,36.999983,-113.459952,M,F,...,Y,C,YNNNNYNN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
995,USGS,370001112575901,B-42-06 32BDB,GW,370001.0,1125759.0,37.000262,-112.967159,M,S,...,Y,C,YYYYNNNN,NaN,111ALVM,NaN,84.0,84.0,NaN,KAN
996,USGS,370006111300401,(D-44- 4) 8bac- 1,GW,370006.0,1113004.0,37.001654,-111.501827,M,S,...,Y,C,Y Y,NaN,227GLNC,X,NaN,NaN,NaN,971600203
1000,USGS,370010111302501,(D-44- 4) 7aab- 1,GW,370010.0,1113025.0,37.002765,-111.507661,M,F,...,Y,C,YYNNNYNN,NaN,NaN,NaN,800.0,800.0,D,464900200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32695,USGS,415956112525201,(B-15- 9)28cbc- 1,GW,415956.0,1125252.0,41.998808,-112.881929,M,S,...,Y,C,YNNNNNNN,NaN,100VLFL,NaN,400.0,NaN,O,NaN
32696,USGS,415956112532501,(B-15- 9)29dbc- 1,GW,415956.0,1125325.0,41.998808,-112.891096,M,S,...,Y,C,YNNNNNNN,NaN,100VLFL,NaN,480.0,NaN,O,NaN
32697,USGS,415957112411001,(B-15- 7)30cbc- 1,GW,415957.0,1124110.0,41.999086,-112.686923,M,S,...,Y,C,YNNNNNNN,NaN,NaN,NaN,228.0,NaN,NaN,NaN
32698,USGS,415958111242901,(A-15- 5)32dbb- 1,GW,415958.0,1112429.0,41.999377,-111.408818,M,T,...,Y,U,NYNNNNNN,NaN,NaN,NaN,191.0,191.0,NaN,NaN
32699,USGS,415958112390301,(B-15- 7)29dac- 1,GW,415958.0,1123903.0,41.999364,-112.651644,M,S,...,Y,C,YNNNNNNN,NaN,NaN,NaN,175.0,NaN,NaN,NaN

In [4]:
#create a list of all wells mentioned in the NWIS of USGS


#Drop any duplicates in the sites to be able to have a list of the wells


dropppeddata = dfsitesGW.drop_duplicates(subset='site_no').copy()


unique_sites = dfsitesGW['site_no'].drop_duplicates()
unique_sites

#or use this one, but both give the same number of rows but it keeps the whole data:

siteslist = dfsitesGW.drop_duplicates(subset=['site_no'], keep='first')

if siteslist['dec_lat_va'].isna().any():
    print("There are NA values in the 'latitude' column.")

    
if siteslist['dec_long_va'].isna().any():
    print("There are NA values in the 'longitude' column.")

#NA_drop = df.dropna(subset=['dec_lat_va', 'dec_long_va'])


np.savetxt(r'C:\Users\jihad\Desktop\jihad\hydroteam\logan_wells\unique_sites.txt', unique_sites, fmt='%s')
np.savetxt(r'C:\Users\jihad\Desktop\jihad\hydroteam\logan_wells\siteslist.txt', siteslist, fmt='%s')

In [5]:
siteslist

,agency_cd,site_no,station_nm,site_tp_cd,lat_va,long_va,dec_lat_va,dec_long_va,coord_meth_cd,coord_acy_cd,...,local_time_fg,reliability_cd,gw_file_cd,nat_aqfr_cd,aqfr_cd,aqfr_type_cd,well_depth_va,hole_depth_va,depth_src_cd,project_no
993,USGS,365954110163301,(D-43-15)32dcd- 1,GW,365954.0,1101633.0,36.998334,-110.276521,M,S,...,Y,C,NNNNNNNN,N300COPLTS,310DCLL,U,120.0,120.0,R,474923900
994,USGS,370000113273301,(C-43-14)31ddd- 1,GW,370000.0,1132733.0,36.999983,-113.459952,M,F,...,Y,C,YNNNNYNN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
995,USGS,370001112575901,B-42-06 32BDB,GW,370001.0,1125759.0,37.000262,-112.967159,M,S,...,Y,C,YYYYNNNN,NaN,111ALVM,NaN,84.0,84.0,NaN,KAN
996,USGS,370006111300401,(D-44- 4) 8bac- 1,GW,370006.0,1113004.0,37.001654,-111.501827,M,S,...,Y,C,Y Y,NaN,227GLNC,X,NaN,NaN,NaN,971600203
1000,USGS,370010111302501,(D-44- 4) 7aab- 1,GW,370010.0,1113025.0,37.002765,-111.507661,M,F,...,Y,C,YYNNNYNN,NaN,NaN,NaN,800.0,800.0,D,464900200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32695,USGS,415956112525201,(B-15- 9)28cbc- 1,GW,415956.0,1125252.0,41.998808,-112.881929,M,S,...,Y,C,YNNNNNNN,NaN,100VLFL,NaN,400.0,NaN,O,NaN
32696,USGS,415956112532501,(B-15- 9)29dbc- 1,GW,415956.0,1125325.0,41.998808,-112.891096,M,S,...,Y,C,YNNNNNNN,NaN,100VLFL,NaN,480.0,NaN,O,NaN
32697,USGS,415957112411001,(B-15- 7)30cbc- 1,GW,415957.0,1124110.0,41.999086,-112.686923,M,S,...,Y,C,YNNNNNNN,NaN,NaN,NaN,228.0,NaN,NaN,NaN
32698,USGS,415958111242901,(A-15- 5)32dbb- 1,GW,415958.0,1112429.0,41.999377,-111.408818,M,T,...,Y,U,NYNNNNNN,NaN,NaN,NaN,191.0,191.0,NaN,NaN
32699,USGS,415958112390301,(B-15- 7)29dac- 1,GW,415958.0,1123903.0,41.999364,-112.651644,M,S,...,Y,C,YNNNNNNN,NaN,NaN,NaN,175.0,NaN,NaN,NaN

In [6]:
#select only the first few rows to plot the location of the wells on the map. plotting 
#all of them would take a long time


new_df = siteslist.iloc[:20]
new_df

,agency_cd,site_no,station_nm,site_tp_cd,lat_va,long_va,dec_lat_va,dec_long_va,coord_meth_cd,coord_acy_cd,...,local_time_fg,reliability_cd,gw_file_cd,nat_aqfr_cd,aqfr_cd,aqfr_type_cd,well_depth_va,hole_depth_va,depth_src_cd,project_no
993,USGS,365954110163301,(D-43-15)32dcd- 1,GW,365954.0,1101633.0,36.998334,-110.276521,M,S,...,Y,C,NNNNNNNN,N300COPLTS,310DCLL,U,120.0,120.0,R,474923900
994,USGS,370000113273301,(C-43-14)31ddd- 1,GW,370000.0,1132733.0,36.999983,-113.459952,M,F,...,Y,C,YNNNNYNN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
995,USGS,370001112575901,B-42-06 32BDB,GW,370001.0,1125759.0,37.000262,-112.967159,M,S,...,Y,C,YYYYNNNN,NaN,111ALVM,NaN,84.0,84.0,NaN,KAN
996,USGS,370006111300401,(D-44- 4) 8bac- 1,GW,370006.0,1113004.0,37.001654,-111.501827,M,S,...,Y,C,Y Y,NaN,227GLNC,X,NaN,NaN,NaN,971600203
1000,USGS,370010111302501,(D-44- 4) 7aab- 1,GW,370010.0,1113025.0,37.002765,-111.507661,M,F,...,Y,C,YYNNNYNN,NaN,NaN,NaN,800.0,800.0,D,464900200
1001,USGS,370010113002001,(C-43-10)32dca-1,GW,370010.0,1130020.0,37.002778,-113.005556,U,U,...,Y,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018PSSWUD
1003,USGS,370017113002001,(C-43-10)32dba-1,GW,370017.0,1130020.0,37.004722,-113.005556,U,U,...,Y,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018PSSWUD
1006,USGS,370021110174201,(D-43-15)31acc- 1,GW,370021.0,1101742.0,37.005833,-110.295688,M,S,...,Y,C,YNNNNNNN,NaN,310DCLL,U,225.0,225.0,O,474923900
1008,USGS,370026110173801,(D-43-15)31aca- 1,GW,370026.0,1101738.0,37.007222,-110.294576,M,S,...,Y,C,YYNYNNNN,NaN,111ALVM,U,50.0,60.0,D,474923900
1011,USGS,370033111374701,(D-44- 3) 6cac-1,GW,370033.0,1113747.0,37.009167,-111.629722,U,U,...,Y,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018PSSWUD
1012,USGS,370034113290801,(C-43-15)25cdd- 1,GW,370034.0,1132908.0,37.009427,-113.486341,G,R,...,Y,C,Y Y,NaN,NaN,NaN,384.0,405.0,L,971600203
1014,USGS,370036113282801,(C-43-14)31bbb- 1,GW,370036.0,1132828.0,37.009983,-113.475230,M,F,...,Y,C,NYNNNYNN,NaN,NaN,NaN,NaN,NaN,NaN,464900300
1015,USGS,370037113281401,(C-43-14)31bab- 1,GW,370037.0,1132814.0,37.010260,-113.471341,M,S,...,Y,C,YY Y,NaN,100ALVM,X,200.0,290.0,D,971600203
1016,USGS,370045113284201,(C-43-15)25ddd- 1,GW,370045.0,1132842.0,37.012483,-113.479119,M,F,...,Y,C,YYNNNYNN,NaN,NaN,NaN,144.0,NaN,NaN,464900200
1017,USGS,370050112274501,(C-44- 5) 6cbb- 1,GW,370050.0,1122745.0,37.013875,-112.463256,M,F,...,Y,U,YYNNNYNN,NaN,NaN,NaN,80.0,NaN,NaN,464900200
1019,USGS,370102111331201,(D-44- 3) 2bad-1,GW,370102.0,1113312.0,37.017222,-111.553333,U,U,...,Y,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018PSSWUD
1021,USGS,370116110183301,(D-43-14)25adc- 1,GW,370116.0,1101833.0,37.021111,-110.309854,M,S,...,Y,C,NNNNNNNN,NaN,NaN,U,NaN,NaN,NaN,474923900
1022,USGS,370120113555201,(C-43-19)25bbb- 1,GW,370120.0,1135552.0,37.022199,-113.931911,M,F,...,Y,C,YYNNNYNN,NaN,NaN,NaN,818.0,818.0,S,474921900
1023,USGS,370125111360801,(D-43- 3)32dca- 2,GW,370125.0,1113608.0,37.023597,-111.602942,M,F,...,Y,U,YNNNNNNN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1024,USGS,370125113190001,(C-43-13)28ab - 1,GW,370125.0,1131900.0,37.023595,-113.317449,M,F,...,Y,C,NYNNNNNN,NaN,NaN,NaN,3000.0,NaN,NaN,NaN

In [7]:
map = folium.Map(location=[39.25, -111.45], zoom_start=8)
for index, row in new_df.iterrows():
    folium.Marker(location=[row['dec_lat_va'], row['dec_long_va']], 
                  popup=row['site_no']).add_to(map)
map.save('map.html')
    
    
    
# browser = webdriver.Firefox()
# browser.get(map._repr_html_())
# browser.save_screenshot(r'C:\Users\jihad\Desktop\jihad\hydroteam\logan_wells\map.png')
# browser.quit()

    
# fig, ax = plt.subplots()
# mplleaflet.show(fig=ax.figure)
# plt.savefig(r'C:\Users\jihad\Desktop\jihad\hydroteam\logan_wells\map.png')


#map.save(r'C:\Users\jihad\Desktop\jihad\hydroteam\logan_wells\map.html')

In [8]:
#this is to draw the map for all the sites, but because the list is very long, the laptop will not be able to do it. 



# map = folium.Map(location=[39.25, -111.45], zoom_start=8)
# for index, row in siteslist.iterrows():
#     folium.Marker(location=[row['dec_lat_va'], row['dec_long_va']], 
#                   popup=row['site_no']).add_to(map)
# map